### ISSUE TITLE
Android Studio2.3.1编译加载后台报错

### ISSUE THREAD

**Issue by hdfs010** [jaydenxiao2016/AndroidFire#31]
修改虚拟机
apply plugin: 'com.android.application'
def releaseTime() {
    return new Date().format("yyyyMMdd", TimeZone.getTimeZone("UTC"))
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "jaydenxiao.com.androidfire"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 4
        versionName "1.0.3"
    }
    buildTypes {
        release {
            buildConfigField "boolean", "LOG_DEBUG", "false"
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            //apk命名
            android.applicationVariants.all { variant ->
                variant.outputs.each { output ->
                    def outputFile = output.outputFile
                    if (outputFile != null && outputFile.name.endsWith('.apk')) {
                        //这里修改apk文件名
                        def fileName = "AndroidFire-${defaultConfig.versionCode}-${defaultConfig.versionName}-${releaseTime()}.apk"
                        output.outputFile = new File(outputFile.parent, fileName)
                    }
                }
            }
        }
        debug{
            buildConfigField "boolean", "LOG_DEBUG", "true"
        }
    }
    //设置虚拟机堆内存空间大小，避免在编译期间OOM
    dexOptions {
        javaMaxHeapSize "4g"
    }
    //打包不检查
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile project(':library:photoPicker')//图片选择
    compile project(':library:irecyclerview')//万能适配器和recyclerview
    compile project(':library:oneKeyShareSDK')//分享
    compile project(':library:jcvideoplayer')//视频播放
    compile project(':library:selectordialog')//常用提示框

}

然后编译通过后 安装成功 后台回报如下错误 
另外这个楼主，是不是升级可以升级一下😄
com.squareup.retrofit2:retrofit:2.0.0-beta3
io.reactivex:rxjava:1.0.1
io.reactivex:rxandroid:1.0.1

-04 05:16:14.119 1309-1309/? D/dalvikvm: Not late-enabling CheckJNI (already on)
05-04 05:16:14.819 1309-1309/jaydenxiao.com.androidfire I/MultiDex: VM with version 1.6.0 does not have multidex support
05-04 05:16:14.819 1309-1309/jaydenxiao.com.androidfire I/MultiDex: install
05-04 05:16:14.839 1309-1309/jaydenxiao.com.androidfire I/MultiDex: MultiDexExtractor.load(/data/app/jaydenxiao.com.androidfire-1.apk, false)
05-04 05:16:14.849 1309-1309/jaydenxiao.com.androidfire I/MultiDex: Detected that extraction must be performed.
05-04 05:16:15.489 1309-1309/jaydenxiao.com.androidfire I/MultiDex: load found 0 secondary dex files
05-04 05:16:15.489 1309-1309/jaydenxiao.com.androidfire I/MultiDex: install done
05-04 05:16:15.749 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
05-04 05:16:15.749 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
05-04 05:16:15.759 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve interface method 20160: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
05-04 05:16:15.759 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
05-04 05:16:15.759 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
05-04 05:16:15.759 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve interface method 20164: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
05-04 05:16:15.759 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
05-04 05:16:15.809 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.view.Window.setStatusBarColor, referenced from method com.jaydenxiao.common.daynightmodeutils.ChangeModeController.refreshStatusBar
05-04 05:16:15.809 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve virtual method 20182: Landroid/view/Window;.setStatusBarColor (I)V
05-04 05:16:15.809 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x6e at 0x0023
05-04 05:16:15.849 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.view.Window.setStatusBarColor, referenced from method com.jaydenxiao.common.commonwidget.StatusBarCompat.setStatusBarColor
05-04 05:16:15.859 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve virtual method 20182: Landroid/view/Window;.setStatusBarColor (I)V
05-04 05:16:15.859 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x6e at 0x0028
05-04 05:16:15.859 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.view.Window.setStatusBarColor, referenced from method com.jaydenxiao.common.commonwidget.StatusBarCompat.translucentStatusBar
05-04 05:16:15.859 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve virtual method 20182: Landroid/view/Window;.setStatusBarColor (I)V
05-04 05:16:15.869 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x6e at 0x0038
05-04 05:16:15.869 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.view.Window.setStatusBarColor, referenced from method com.jaydenxiao.common.commonwidget.StatusBarCompat.translucentStatusBar
05-04 05:16:15.869 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve virtual method 20182: Landroid/view/Window;.setStatusBarColor (I)V
05-04 05:16:15.869 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x6e at 0x0049
05-04 05:16:16.049 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: GC_FOR_ALLOC freed 240K, 14% free 3431K/3960K, paused 82ms, total 85ms
05-04 05:16:16.129 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawable
05-04 05:16:16.129 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve virtual method 1035: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
05-04 05:16:16.129 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
05-04 05:16:16.149 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.ResourcesWrapper.getDrawableForDensity
05-04 05:16:16.149 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve virtual method 1037: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
05-04 05:16:16.149 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
05-04 05:16:16.199 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
05-04 05:16:16.199 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve virtual method 1072: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
05-04 05:16:16.199 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
05-04 05:16:16.199 1309-1309/jaydenxiao.com.androidfire I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
05-04 05:16:16.209 1309-1309/jaydenxiao.com.androidfire W/dalvikvm: VFY: unable to resolve virtual method 1094: Landroid/content/res/TypedArray;.getType (I)I
05-04 05:16:16.209 1309-1309/jaydenxiao.com.androidfire D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
05-04 05:16:16.419 1309-1309/jaydenxiao.com.androidfire W/System.err: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
05-04 05:16:16.509 1309-1309/jaydenxiao.com.androidfire W/System.err:     at com.jaydenxiao.common.commonutils.TUtil.getT(TUtil.java:12)
05-04 05:16:16.509 1309-1309/jaydenxiao.com.androidfire W/System.err:     at com.jaydenxiao.common.base.BaseActivity.onCreate(BaseActivity.java:74)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.Activity.performCreate(Activity.java:5231)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:135)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.os.Looper.loop(Looper.java:136)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5017)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at dalvik.system.NativeStart.main(Native Method)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at com.jaydenxiao.common.commonutils.TUtil.getT(TUtil.java:12)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at com.jaydenxiao.common.base.BaseActivity.onCreate(BaseActivity.java:75)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.Activity.performCreate(Activity.java:5231)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:135)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.os.Looper.loop(Looper.java:136)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5017)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
05-04 05:16:16.519 1309-1309/jaydenxiao.com.androidfire W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by jaydenxiao2016** [comment]
这是一些警告，你可以升级版本，或者在混淆文件设置相应忽略警告
