### ISSUE TITLE
为什么你的BaseFragment里面有对Model的引用？

### ISSUE THREAD

**Issue by leguang** [jaydenxiao2016/AndroidFire#4]
为什么你的BaseFragment里面有对Model的引用？
`     mPresenter = TUtil.getT(this, 0);
        mModel= TUtil.getT(this,1);`

我看到你的代码里在BaseFragment里通过反射创建了Model的实例，请问MVP模式当中，View层不是不应该持有Model的实力对象吗？

**Comment by wjploop** [comment]
UTill.getT(thii,1);
这个方法报错怎么解决？
查了了这个问题，，基础不好看不懂，希望指点下，在此谢过了．
0-10 19:35:50.254 12596-12596/loop.com.testforcommon W/System.err: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
10-10 19:35:50.254 12596-12596/loop.com.testforcommon W/System.err:     at com.jaydenxiao.common.commonutils.TUtil.getT(TUtil.java:12)
10-10 19:35:50.254 12596-12596/loop.com.testforcommon W/System.err:     at com.jaydenxiao.common.base.BaseActivity.onCreate(BaseActivity.java:75)
10-10 19:35:50.254 12596-12596/loop.com.testforcommon W/System.err:     at android.app.Activity.performCreate(Activity.java:6367)

**Comment by 385841539** [comment]
要是能出个视频教程绝对6 的不行 ，

**Comment by Greathfs** [comment]
这套框架 的确V里面持有M的引用，感觉偏离MVP思想了，有点像MVC，BaseActivity和BaseFragment都是 层主可以去参考下T-MVP现有的解决办法，那套框架和这个基本上是一致的

**Comment by yuzhongrong** [comment]
view里面是不能持有m的引用的   ，m引用应该在p层持有的具体请参考腾讯的bugly 框架设计
