### ISSUE TITLE
自己项目引入该项目中的视频模块报错

### ISSUE THREAD

**Issue by sunkeding** [jaydenxiao2016/AndroidFire#42]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.leoao.fitness-2/base.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.leoao.fitness-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.leoao.fitness-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                    at java.lang.System.loadLibrary(System.java:988)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:209)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:205)
                                                                    at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:196)
                                                                    at fm.jiecao.jcvideoplayer_lib.JCMediaManager.<init>(JCMediaManager.java:56)
                                                                    at fm.jiecao.jcvideoplayer_lib.JCMediaManager.instance(JCMediaManager.java:50)
                                                                    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.addTextureView(JCVideoPlayer.java:332)
                                                                    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.addTextureView(JCVideoPlayerStandard.java:176)
                                                                    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareVideo(JCVideoPlayer.java:230)
                                                                    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.prepareVideo(JCVideoPlayerStandard.java:215)
                                                                    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:188)
                                                                    at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:182)
                                                                    at android.view.View.performClick(View.java:4785)
                                                                    at android.view.View$PerformClick.run(View.java:19888)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5276)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by jaydenxiao2016** [comment]
是不是so文件没加上
